# Generated by Django 5.1 on 2024-10-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Maintenance', 'verbose_name_plural': 'Maintenance'},
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['equipment', 'name'], name='api_mainten_equipme_834f5a_idx'),
        ),
    ]
