# Generated by Django 5.1 on 2024-10-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_maintenance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='maintenance',
            name='api_mainten_equipme_834f5a_idx',
        ),
    ]
