# Generated by Django 5.1 on 2024-10-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_maintenance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='initial_hour_maintenance',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas da Peça'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='alarm_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas para Alarme'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='remaining_hours',
            field=models.FloatField(default=0, editable=False, verbose_name='Remaining Hours'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='worked_hours',
            field=models.FloatField(default=0, editable=False, verbose_name='Worked Hours'),
        ),
    ]
