# Generated by Django 5.1 on 2024-10-29 16:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_maintenance_initial_hour_maintenance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_hours',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='initial_hour_maintenance',
            field=models.FloatField(default=0, verbose_name='Initial Maintenance Hour'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='alarm_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='remaining_hours',
            field=models.FloatField(default=0, verbose_name='Remaining Hours'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='worked_hours',
            field=models.FloatField(default=0, verbose_name='Worked Hours'),
        ),
    ]
