# Generated by Django 5.1 on 2024-10-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_maintenance_maintenance_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_date', models.DateTimeField(auto_now_add=True)),
                ('equipment_worked_hours', models.FloatField(default=0, verbose_name='Worked Hours Equipment')),
                ('maintenance_worked_hours', models.FloatField(default=0, verbose_name='Worked Hours Maintenance')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_logs', to='api.maintenance')),
            ],
        ),
    ]
