# Generated by Django 5.1 on 2024-10-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_maintenanceresetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceresetlog',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
